# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170318_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号码'),
        ),
    ]
